shoppingproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

shoppingproject/eproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shoppingproject/searchapp/urls.py
from django.urls import path
from . import views

app_name = 'searchapp'

urlpatterns = [
    path('', views.searchresult, name='searchresult'),
]

shoppingproject/shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('', views.allprodcat, name='allprodcat'),
    path('<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodetail, name='prodcatdetail'),
]

shoppingproject/cart/models.py
from django.db import models
from shop.models import *
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shoppingproject/searchapp/models.py
from django.db import models

# Create your models here.

shoppingproject/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodcatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name', )
        verbose_name = 'product'
        verbose_name_plural = 'products'

shoppingproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

shoppingproject/searchapp/views.py
from django.shortcuts import render
from shop.models import *
from django.db.models import Q
# Create your views here.

def searchresult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

shoppingproject/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from .models import *


# Create your views here.


def allprodcat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, "category.html", {'category': c_page, 'products': products})


def prodetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

shoppingproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block meta %}{% endblock %}">
    <script src="https://kit.fontawesome.com/37140be1a3.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <div class="d-flex flex-column min-vh-100">
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

shoppingproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
Here is your Cart!
{% endblock %}

{% block title %}
Cart
{% endblock %}

{% block content %}
{% if not cart_items %}
<div class="text-center">
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is Empty!
        </h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'shop:allprodcat' %}">Here</a> to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div class="container">
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            <b>Your Shopping Cart</b>
        </h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">Your Items</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" style="width: 100px;" class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Price: $ {{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x {{cart_item.product.name}}
                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-sharp fa-solid fa-plus custom_icon"></i></a>
                        &emsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-sharp fa-solid fa-minus custom_icon"></i></a>
                        &emsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa-sharp fa-solid fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                    <td>
<!--                         <a href="" class="custom_a"><i class="fa-sharp fa-solid fa-plus custom_icon_disbaled"></i></a>-->
                        &emsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-sharp fa-solid fa-minus custom_icon"></i></a>
                        &emsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa-sharp fa-solid fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class=" table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>Checkout</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Please review your shopping cart items before checkout!</td>
                </tr>
                <tr>
                    <td class="text-left">Your Total is: <strong>$ {{total}}</strong></td>
                </tr>
                </tbody>
            </table>
            <div class="d-flex justify-content-center">
                <div class="mx-2">
                    <a href="{% url 'shop:allprodcat' %}" class="btn btn-secondary btn-block custom_button">Continue Shopping</a>
                </div>
                <div class="mx-2">
                    <a href="{% url 'shop:allprodcat' %}" class="btn btn-warning btn-block custom_button">Make Payment</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

shoppingproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to URBAN  TROVE!
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - URBAN TROVE
    {% else %}
        Lookout for Amazing Deals! - URBAN TROVE
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p><a href="{% url 'shop:allprodcat' %}">Our Collections</a> </p>

                </div>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
        <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{ category.name }}</h1>
        <p class="text-justify">{{ category.description }}</p>
    </div>
    {% else %}
    <div>
        <img class="my_image" src="{% static 'img/ut_banner.png' %}" alt="Our Proucts" style="width: 100%; height: auto;">
    </div>
    <br>
    <div class="container-fluid"  style="max-width: 90%;">
        <h1 class="text-center my_title">Our Collections</h1>
        <p class="text-center">Welcome to Our Collections: Where Style Meets Urban Edge. Discover the heart and soul of our urban clothing site as you explore our meticulously curated collections. Immerse yourself in a world of fashion-forward designs that effortlessly blend streetwear with contemporary trends. From statement-making tops to head-turning bottoms, our collections embody the vibrant spirit of urban culture. Unleash your personal style and express your individuality with our carefully selected pieces that capture the essence of urban fashion. Whether you're seeking bold prints, edgy details, or versatile essentials, Our Collections page is your gateway to a diverse range of urban-inspired outfits that will make you stand out from the crowd. Step into the urban fashion scene and unleash your unique style with our extraordinary collections.</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx-auto">
            {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}" ></a>
                    <div class="card-body">
                        <h4>{{ product.name }}</h4>
                        <p>${{ product.price }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

shoppingproject/templates/footer.html
<div class="footer navbar-fixed-bottom myfooter">
  <p class="text-center">
    &copy; URBAN TROVE Clothing Co. All Rights Reserved
  </p>
</div>

shoppingproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop:allprodcat' %}"> <img src="{% static 'img/ut_logo.png' %}" alt="load img" width="70px" height="70px"></a>
  </center>
</header>

shoppingproject/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'shop:allprodcat' %}">
      <img src="{% static 'img/logo.png' %}" alt="Bootstrap"  height="50">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allprodcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
              {% endfor %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">My Cart</a></li>
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}">My Cart<i class="fa-sharp fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

shoppingproject/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{{ product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} - URBAN TROVE
    {% endif %}
{% endblock %}

{% block content %}
<div class="row container">
  <div class="mx-auto">
    <p><a href="{% url 'shop:allprodcat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</p>
  </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width: 18rem;">
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <h1 class="my_prod_title">{{ product.name }}</h1>
        <p>${{ product.price }}</p>
        <h3 class="my_title"><b>Product Description:</b></h3>
        <p class="text-justify my_prod_text">{{ product.description }}</p>
        {% if product.stock == 0 %}
        <p class="text-justify my_prod_text"><b>Out Of Stock!</b></p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}"><b>Add to Cart</b></a>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

shoppingproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
Welcome to URBAN  TROVE :)
{% endblock %}

{% block title %}
Search

{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width: 18rem;">
                <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}" ></a>
                <div class="card-body">
                    <h4>{{ product.name }}</h4>
                    <p>${{ product.price }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found!</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}