movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()


class Movies(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField()

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import *


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import *
from . forms import MovieForm
# Create your views here.

def index(request):
    movie = Movies.objects.all()
    context = {'movie_list': movie}
    return render(request, 'index.html', context)

def detail(request, movie_id):
    movie = Movies.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie':movie})

def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['image']
        movie = Movies(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')

def update(request, id):
    movie = Movies.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request, id):
    if request.method == 'POST':
        movie = Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<div class="form-container"><br>
  <h2 class="form-title">ADD MOVIE</h2>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Movie Name">
    <input type="text" name="desc" placeholder="Movie Description">
    <input type="text" name="year" placeholder="Movie Release Year">
    <input type="file" name="image">
    <input type="submit" value="Submit">
  </form>
</div>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
      .form-container {
        max-width: 400px;
        margin: 0 auto;
      }

      .form-container input[type="text"],
      .form-container input[type="file"],
      .form-container input[type="submit"] {
        display: block;
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 16px;
        box-sizing: border-box;
      }

      .form-container input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        cursor: pointer;
      }

      .form-container input[type="submit"]:hover {
        background-color: #45a049;
      }

      .form-title {
        text-align: center;
        font-size: 24px;
        margin-bottom: 20px;
      }
    </style>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">MovieHub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movieapp:index' %}">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
      </li>
    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  Delete this movie?<br>
  <input type="submit" value="Delete">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <img src="{{ movie.img.url }}" style="height: 250px; margin: 10px; background-size: cover;">
    </div>
    <div class="col-md-8">
      <h1>{{ movie.name }} ({{ movie.year }})</h1>
      <p style="max-width: 700px;">{{ movie.desc }}</p>
      <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
      <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
    </div>
  </div>
</div>

{% endblock %}

movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<br>
<div class="container">
<div class="card-deck">
    {% for i in movie_list %}
  <div class="card">
    <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" >
    <div class="card-body">
      <h5 class="card-title">{{ i.name }} ({{ i.year }})</h5>
      <p class="card-text"><small class="text-muted">{{ i.year }}</small></p>
      <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>
    </div>
  </div>
    {% endfor %}

</div>
</div>
{% endblock %}